name: Test AWS Secrets

on:
  push:
    branches:
      - main  

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display AWS Region
        run: echo "AWS_REGION is ${{ secrets.AWS_REGION }}"

      - name: Validate AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

          aws sts get-caller-identity
